//this will wrap up the autogenerated informated in const char*, so the touch command won't be necessary anymore
//and dependencies should work again (we just have to delete the corresponding obj. file?)
// 

#include "version_info.h"

#define VERSION_FULLVERSION4 VERSION4_WITH_PERIOD(MAJOR_VERSION,MINOR_VERSION,MICRO_VERSION,BUILD_VERSION)
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)
#define VERSION_STRING STRINGIZE(MAJOR_VERSION) "." STRINGIZE(MINOR_VERSION) "." STRINGIZE(MICRO_VERSION) "." STRINGIZE(BUILD_VERSION)


const char* strVersionFullVersion = VERSION_STRING;

const char* strVersionBuildDate			= __DATE__;
const char* strVersionBuildTime			= __TIME__;
